### ISSUE TITLE
Issues when training on the ALUS subset data

### ISSUE THREAD

**Issue by f-macfarlane95** [Schnei1811/InsectClassifier#1]
The `batch_size` input argument does not affect the training at all when using the linked data and functions, specifically within `createData()`. I have attempted to alter the way the numpy arrays are saved in `metadata/foldername/Arrays_Batches`. However, this is then changed when the entire dataset is saved in `Arrays_Data` and loaded all at ones regardless of the batch size. This cases every image to be loaded resulting in a memory exception. I notice this work has now been published, is there an updated version of the model available?

**Comment by Schnei1811** [comment]
Hi f-macfarlane. Thanks for reaching out! How many images are you using for data? It sounds like the complete data_array isn't fitting into your RAM. How much RAM do you have? batch_size is used for the number of images used at a time for training the model using your GPU. If you can confirm I can help you work through the problem. First thing I would try would be to use a small subset of your data and see if you can train a model. 

An updated version of the system will be coming out in a few weeks time actually! A complete overhaul that should be much improved overall. Keep me posted
